# Generated by Django 4.1.2 on 2022-11-17 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('breed', models.TextField()),
                ('eartag', models.TextField()),
                ('age', models.PositiveIntegerField()),
                ('type', models.TextField()),
                ('weight', models.PositiveIntegerField()),
            ],
        ),
    ]
