# Generated by Django 4.1.2 on 2022-11-18 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cowapp', '0003_vaccine'),
    ]

    operations = [
        migrations.CreateModel(
            name='Eartag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.TextField()),
                ('previoustag', models.TextField()),
            ],
        ),
    ]
