# Generated by Django 3.2.2 on 2022-12-06 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cowapp', '0009_orders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.ImageField(upload_to='product_image/'),
        ),
    ]
